server:
  port: 8010

spring:
  application:
    name: discoveryservice

eureka:
#  instance:
#   hostname: localhost
#   port: 8010

  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: true