server:
  port: 8082
spring:
  application:
    name: email-service

eureka:
  client:
#    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      register-with-eureka: true
      fetch-registry: true
#    registerWithEureka: false
#    fetchRegistry: false
