server:
  port: 8090
spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/biswajit1983/spring-microservice-test
            search-paths:
              - "EmailServiceConfigProperties/{application}/{profile}"
          health:
            enabled: true
      name: config-service
management:
  endpoint:
    health:
      show-details: always