spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reckoNew?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&relaxAutoCommit=true
    username: root
    password: recko123
    auto-commit: false
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: reckon-new-1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.id.new_generator_mappings: true
      hibernate.connection.autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: update
      hibernate.jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic:
      userRegistered: USER_REGISTERED_TOPIC
security:
  basic:
    enabled: false